name: Build

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/setup-node.yml
    with:
      script: npm run build
      uploadArtifact: |
        .
        logs
      artifactName: frontend-build
